In [2]:
import uproot
import matplotlib.pyplot as plt
import numpy as np


In [6]:
np.random.seed(1)

events = uproot.open("/mnt/d/data/gemtrd/003200_v9_hists.root")["events"]
events.keys()

['srs_raw_count',
 'srs_raw_roc',
 'srs_raw_slot',
 'srs_raw_channel',
 'srs_raw_apv_id',
 'srs_raw_channel_apv',
 'srs_raw_best_sample',
 'srs_raw_samples_index',
 'srs_raw_samples_count',
 'srs_raw_samples',
 'f125_wraw_count',
 'f125_wraw_roc',
 'f125_wraw_slot',
 'f125_wraw_channel',
 'f125_wraw_invalid_samples',
 'f125_wraw_overflow',
 'f125_wraw_itrigger',
 'f125_wraw_samples_index',
 'f125_wraw_samples_count',
 'f125_wraw_samples',
 'f250_wraw_count',
 'f250_wraw_roc',
 'f250_wraw_slot',
 'f250_wraw_channel',
 'f250_wraw_invalid_samples',
 'f250_wraw_overflow',
 'f250_wraw_itrigger',
 'f250_wraw_samples_index',
 'f250_wraw_samples_count',
 'f250_wraw_samples',
 'f125_pulse_count',
 'f125_pulse_roc',
 'f125_pulse_slot',
 'f125_pulse_channel',
 'f125_pulse_npk',
 'f125_pulse_le_time',
 'f125_pulse_time_quality_bit',
 'f125_pulse_overflow_count',
 'f125_pulse_pedestal',
 'f125_pulse_integral',
 'f125_pulse_peak_amp',
 'f125_pulse_peak_time',
 'f125_pulse_word1',
 'f125_pulse_word2'

Now we need to extract number of time-bins for each channel.
The number is actually the same for the whole run, so we need to get only one element

In [ ]:
events['srs_raw_samples_count'].array(library="np", entry_start=entry_start, entry_stop=entry_start+1)[0][0]

In [7]:
type(events)

uproot.models.TTree.Model_TTree_v20

In [9]:
entry_start = 2
entry_stop = 10
# 'srs_raw_channel',
# 'srs_raw_apv_id',
# 'srs_raw_channel_apv',
# 'srs_raw_best_sample',
# 'srs_raw_samples_index',
# 'srs_raw_samples_count',

all = events['srs_raw_samples'].array(library="np", entry_start=entry_start, entry_stop=entry_stop)


array([array([2820, 2810, 2717, ..., 2881, 2872, 2868], dtype=uint16),
       array([2886, 2814, 2757, ..., 2904, 2908, 2899], dtype=uint16),
       array([2847, 2755, 2788, ..., 2882, 2883, 2893], dtype=uint16),
       array([2831, 2710, 2758, ..., 2873, 2835, 2818], dtype=uint16),
       array([2742, 2808, 2891, ..., 2880, 2875, 2902], dtype=uint16),
       array([2777, 2807, 2879, ..., 2903, 2917, 2895], dtype=uint16),
       array([2724, 2816, 2848, ..., 2865, 2864, 2881], dtype=uint16),
       array([2830, 2734, 2797, ..., 2876, 2885, 2917], dtype=uint16)],
      dtype=object)

In [10]:
entry_start = 2
entry_stop = 10
# 'srs_raw_channel',
# 'srs_raw_apv_id',
# 'srs_raw_channel_apv',
# 'srs_raw_best_sample',
# 'srs_raw_samples_index',
# 'srs_raw_samples_count',

all2 = events['srs_raw_samples'].array(entry_start=entry_start, entry_stop=entry_stop)

 

6

In [12]:
all2[0]

<Array [2820, 2810, 2717, 2774, ..., 2881, 2872, 2868] type='5376 * uint16'>